### PR TITLE
Use DomDocument to extract attributes.

### PR DESCRIPTION
**Pull request by mpatek**

### CODE REVIEW

**Comment by mpatek** [comment]
@danielbachhuber this is a solution for #20. Review/merge please.

**Comment by danielbachhuber** [comment]
Can you make sure there's appropriate test coverage around the change?

**Comment by mpatek** [comment]
@danielbachhuber I'm already testing that the width/height attributes are passed on to the video tag. Any other tests I should run?

**Comment by danielbachhuber** [comment]
> Any other tests I should run?

Variants with how the attributes are formatted.

**Comment by mpatek** [comment]
OK. I've tested with `width="100"` `width='100'` and `width=100`.

**Comment by danielbachhuber** [comment]
:+1:

**Pull request merged**
