### PR TITLE
Readme description and installation details.

### PR DESCRIPTION
**Pull request by mpatek**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@mpatek where's this at now?

**Comment by mpatek** [comment]
@danielbachhuber I wasn't sure if I should link to our `gif2html5-app` repo since it's not open-source yet? Or should we just provide instructions for how any web application would need to behave in order to work with this plugin?

**Comment by danielbachhuber** [comment]
> I wasn't sure if I should link to our gif2html5-app repo since it's not open-source yet?

Linking is fine. It will be open source eventually.

**Comment by mpatek** [comment]
@danielbachhuber OK. How does this look?

**Pull request merged**
