### PR TITLE
Fix autoplay detection

### PR DESCRIPTION
**Pull request by mpatek**
See #58

### CODE REVIEW

**Comment by mpatek** [comment]
@noppanit this seemed to fix the inconsistency for me. Could you test it out and review/merge if it looks OK?

**Comment by noppanit** [comment]
@mpatek this going to fix the play button showing up?

**Comment by noppanit** [comment]
Testing

**Comment by mpatek** [comment]
> this going to fix the play button showing up?

That's what I'm trying for. Thanks.

**Comment by noppanit** [comment]
@mpatek It should be ok. Let's try that.

**Pull request merged**
