### PR TITLE
Avoid traversing down directories

### PR DESCRIPTION
**Pull request by danielbachhuber**
It's not as glam

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@noppanit Can you sanity check this locally to make sure the scripts still load?

**Comment by noppanit** [comment]
It loads but it's at the header and not the footer.

screenshot 2015-05-28 12 53 22

**Comment by danielbachhuber** [comment]
> It loads but it's at the header and not the footer.

Ok. I've created #45 for that. Can you sanity check?

**Comment by noppanit** [comment]
I think it's ready to be merged.

**Pull request merged**
