### PR TITLE
Adding Modernizr-style test.

### PR DESCRIPTION
**Pull request by mpatek**
@see #51

### CODE REVIEW

**Comment by mpatek** [comment]
@goldenapples what do you think of this? I've basically copied the Modernizr `video` and `videoautoplay` tests, and then just do like Modernizr and add a class to the docElement.

@noppanit @danielbachhuber thoughts?

**Comment by mpatek** [comment]
Here's the Modernizr autoplay test: https://github.com/Modernizr/Modernizr/blob/master/feature-detects/video/autoplay.js

And here's the Modernizr video test: https://github.com/Modernizr/Modernizr/blob/master/feature-detects/video.js

**Comment by goldenapples** [comment]
This is good, self-contained so we don't need to specify that theme authors include Modernizr to make this work.

I think you need a little bit more granularity in the classes you add, though. Looks like there's at least three, maybe more, possibilities to distinguish:

* browser supports video & autoplay. cool, let it play.
* browser supports video but not autoplay, or requires a user interaction to play video. ok, show the play button.
* browser can't handle any of the video formats we're serving. they'll see the fallback gif anyway so no need for the play button. 

Otherwise -- or if this isn't actually an issue with real-world browsers -- then it looks good to me.

**Comment by mpatek** [comment]
Excellent feedback, thanks @goldenapples. Now I'm including a video support indicator as well. So the play button should only be shown if we have video support, but no autoplay support.

Do you feel competent to review/merge? Or should I assign to @noppanit?

**Comment by mpatek** [comment]
@noppanit could you review/merge please?

**Comment by noppanit** [comment]
@mpatek It looks good. Thanks a lot Mike.

**Comment by noppanit** [comment]
@mpatek BTW, as we copied the code from Modernizr. Do we have to give credit back to them?

**Comment by mpatek** [comment]
> as we copied the code from Modernizr. Do we have to give credit back to them?

Looks like Modernizr has the [MIT license](http://opensource.org/licenses/MIT) and gif2html5 plugin has the [GPL license](http://www.gnu.org/licenses/gpl-2.0.html)

According to [this](http://en.wikipedia.org/wiki/License_compatibility) MIT is `GPL-compatible`, so I think it's OK to include the Modernizr code, as long as we keep this plugin opensource.

**Comment by noppanit** [comment]
:+1: just want to make sure. Thanks @mpatek

**Pull request merged**
