### PR TITLE
Properly sanitize and escape attributes

### PR DESCRIPTION
**Pull request by danielbachhuber**
From #17

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@mpatek #reviewmerge

**Comment by mpatek** [comment]
@danielbachhuber are there any problems with doubly-`esc_attr`?

**Comment by danielbachhuber** [comment]
> are there any problems with doubly-esc_attr?

Nope — calling it shouldn't cause problems.

**Comment by mpatek** [comment]
OK, this looks fine. Should I wait for Travis?

**Pull request merged**
