### PR TITLE
Replace url with cloudfront url

### PR DESCRIPTION
**Pull request by noppanit**
https://github.com/fusioneng/gif2html5-plugin/issues/28

Something like this.

### CODE REVIEW

**Comment by noppanit** [comment]
@mpatek I'm thinking of something like this.

**Comment by noppanit** [comment]
@mpatek #review?

**Comment by mpatek** [comment]
@noppanit looks good. Thanks for adding those tests. Could you fix those phpcs errors?

**Comment by noppanit** [comment]
Oh hmm don't know how i missed that wilk fix it



Best Regards,
Noppanit Charassinvichai aka Toy

twitter: @noppanit

**Pull request merged**
